reconcile the options between onap-gerrit-review and onap-gerrit-review-step2, update for pom-version-already-released

diff --git a/bin/onap-gerrit-review b/bin/onap-gerrit-review
--- a/bin/onap-gerrit-review
+++ b/bin/onap-gerrit-review
@@ -3,15 +3,16 @@
 # shellcheck disable=SC2197
 # SC2197: allow fgrep
 
-GITVERSIONSTAMP="2022-08-23-15-44"
+GITVERSIONSTAMP="2022-08-30-23-07"
 
 usage()
 {
     exec 1>&2
     [ $# -gt 0 ] && echo "$@"
-    echo "Usage: $0 [-E] [-S] [-x] [-b branch] [-d depth] [-t] [-q] git pull . . ."
-    echo "Usage: $0 [-E] [-S] [-x] [-c] [-t] [-q] local-git-directory-name"
+    echo "Usage: $0 [common-options] [-b branch] [-d depth] git pull . . ."
+    echo "Usage: $0 [common-options] [-c] local-git-directory-name"
     echo "Usage: $0 -V"
+    echo "Common options: [-E] [-S] [-m message] [-t] [-q] [-x] [-Q]"
     echo "To use git pull, click the vertical ... in the browser and grab the Pull string."
     echo "Invoke as $0 git pull . . ."
     echo "For example,"
@@ -27,12 +28,14 @@ usage()
     echo " -C do not clear out .tox, .pytest_cache, *.egg-info, htmlcov directories before scanning"
     echo
     echo "Thse options may always be used:"
-    echo " -S show successes as well as errors (turn off -s in onap-gerrit-review-step2)."
+    echo " -m message - do not report on this message. May be specified multiple times."
+    echo " -E Do not exit non-zero on failures (also can be disabled using '-m exit-code-on-errors')"
     echo " -t When showing leading tabs, show all of them (pass -t to onap-gerrit-review-step2)."
+    echo " -S show successes as well as errors (turn off -s in onap-gerrit-review-step2)."
     echo " -q Do not print a message about how to suppress error/warning messages when there are errors/warnings"
     echo " -Q Force the message to be printed about how to suppress error/warning messages"
-    echo " -E Do not exit 1 on failures"
     echo " -x Turn on -x mode"
+    echo " -X Turn on verbosity mode for sub-components. May be specified multiple times for additional verbosity."
     echo " -V Show the version stamp and exit"
     echo
     echo "Environment variables:"
@@ -53,19 +56,25 @@ ALLTABS=
 EXITCODEONFAILURE=true
 SUPPRESSMESSAGES=
 FORCESUPPRESSMESSAGES=
-while getopts b:Cd:EqQStVx opt
+SUBVERBOSITY=
+RMMESSAGES=
+while getopts b:Cd:Em:qQStVxX opt
 do
     case "$opt" in
 	b ) BRANCH="$OPTARG" ;;
 	C ) CLEAN=false ;;
 	d ) DEPTH="$OPTARG" ;;
 	E ) EXITCODEONFAILURE=false ;;
+	m ) [ -z "$RMMESSAGES" ] && RMMESSAGES="-m"
+	    RMMESSAGES="$RMMESSAGES $(echo "$OPTARG" | sed 's/[[:space:]]/,/g')"
+	    ;;
 	q ) SUPPRESSMESSAGES=-q ;;
 	Q ) FORCESUPPRESSMESSAGES=-Q ;;
 	S ) SILENT= ;;
 	t ) ALLTABS=-a ;;
 	V ) echo "Version: $GITVERSIONSTAMP"; exit 0 ;;
 	x ) set -x ;;
+	X ) SUBVERBOSITY="$SUBVERBOSITY -X" ;;
 	* ) usage ;;
     esac
 done
@@ -151,10 +160,10 @@ scan_local()
 
     mv "$TMPDIR/$GITPATHBASE.sv/.temp.git-log" "$TMPDIR/$GITPATHBASE/.temp.git-log"
 
-    echo Running: onap-gerrit-review-step2 -l $SILENT $ALLTABS $SUPPRESSMESSAGES $FORCESUPPRESSMESSAGES "$TMPDIR/$GITPATHBASE"
-    [ -n "$SILENT" ] && echo To see all messages, use: onap-gerrit-review-step2 -l $ALLTABS $SUPPRESSMESSAGES $FORCESUPPRESSMESSAGES "$TMPDIR/$GITPATHBASE"
+    echo Running: onap-gerrit-review-step2 -l $SILENT $ALLTABS $SUPPRESSMESSAGES $FORCESUPPRESSMESSAGES $SUBVERBOSITY $RMMESSAGES "$TMPDIR/$GITPATHBASE"
+    [ -n "$SILENT" ] && echo To see all messages, use: onap-gerrit-review-step2 -l $ALLTABS $SUPPRESSMESSAGES $FORCESUPPRESSMESSAGES $SUBVERBOSITY $RMMESSAGES "$TMPDIR/$GITPATHBASE"
     :  FORCESUPPRESSMESSAGES= $FORCESUPPRESSMESSAGES
-    onap-gerrit-review-step2 -l $SILENT $ALLTABS $SUPPRESSMESSAGES $FORCESUPPRESSMESSAGES "$TMPDIR/$GITPATHBASE" || exitcode=1
+    onap-gerrit-review-step2 -l $SILENT $ALLTABS $SUPPRESSMESSAGES $FORCESUPPRESSMESSAGES $SUBVERBOSITY $RMMESSAGES "$TMPDIR/$GITPATHBASE" || exitcode=1
 }
 
 scan_git_pull()
@@ -200,10 +209,10 @@ scan_git_pull()
 	*snmptrap* ) diff .temp.git-log .temp.git-log2 ;;
     esac
 
-    echo Running: onap-gerrit-review-step2 -l $SILENT $ALLTABS $SUPPRESSMESSAGES $FORCESUPPRESSMESSAGES "$TMPDIR/$GITPATHBASE"
-    [ -n "$SILENT" ] && echo To see all messages, use: onap-gerrit-review-step2 -l $ALLTABS $SUPPRESSMESSAGES $FORCESUPPRESSMESSAGES "$TMPDIR/$GITPATHBASE"
+    echo Running: onap-gerrit-review-step2 -l $SILENT $ALLTABS $SUPPRESSMESSAGES $FORCESUPPRESSMESSAGES $SUBVERBOSITY $RMMESSAGES "$TMPDIR/$GITPATHBASE"
+    [ -n "$SILENT" ] && echo To see all messages, use: onap-gerrit-review-step2 -l $ALLTABS $SUPPRESSMESSAGES $FORCESUPPRESSMESSAGES $SUBVERBOSITY $RMMESSAGES "$TMPDIR/$GITPATHBASE"
     :  FORCESUPPRESSMESSAGES= $FORCESUPPRESSMESSAGES
-    onap-gerrit-review-step2 -l $SILENT $ALLTABS $SUPPRESSMESSAGES $FORCESUPPRESSMESSAGES "$TMPDIR/$GITPATHBASE" || exitcode=1
+    onap-gerrit-review-step2 -l $SILENT $ALLTABS $SUPPRESSMESSAGES $FORCESUPPRESSMESSAGES $SUBVERBOSITY $RMMESSAGES "$TMPDIR/$GITPATHBASE" || exitcode=1
 }
 
 exitcode=0
